pipeline:
  name: MAIN
  identifier: MAIN
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Main_GITHUB
        build: <+input>
  stages:
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Set up Java
                  identifier: setup_java
                  spec:
                    uses: actions/setup-java@v3
                    with:
                      distribution: temurin
                      java-version: "21"
              - step:
                  type: Run
                  name: Build with Gradle
                  identifier: Build_with_Gradle
                  spec:
                    shell: Sh
                    command: |-
                      cd apex-airline-system/backend
                      ./gradlew test
                  description: Run Gradle tests
              - step:
                  type: Run
                  name: Make gradlew Executable
                  identifier: make_gradlew_executable
                  spec:
                    shell: Sh
                    command: chmod +x gradlew
                    workingDirectory: apex-airline-system/backend
                  description: Make gradlew executable
              - step:
                  type: Run
                  name: Build and Analyze
                  identifier: build_and_analyze
                  spec:
                    shell: Sh
                    command: ./gradlew build sonar --info
                    workingDirectory: apex-airline-system/backend
                    env:
                      SONAR_TOKEN: sqp_cbae4db0807d59ee0ec9c1fbd37921302565b15b
                      SONAR_HOST_URL: https://vbbxhpxt-9000.use.devtunnels.ms
                  description: Build and analyze with SonarQube
          caching:
            enabled: false
            paths: []
        delegateSelectors:
          - docker-delegate
  notificationRules:
    - name: Failure-Email
      identifier: FailureEmail
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - jpestrada@unis.edu.gt
            - juanpablo08082002@hotmail.com
      enabled: true
