pipeline:
  name: MAIN
  identifier: MAIN
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Main_GITHUB
        build: <+input>
  stages:
    - stage:
        name: UNIT TEST
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              dockerImage: temurin:21-jdk
          execution:
            steps:
              - step:
                  type: Run
                  name: Unit testing
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cd apex-airline-system/backend
                      pwd
                      ls -la
                      ./gradlew test
                  description: Backend_Test
          caching:
            enabled: false
            paths: []
        delegateSelectors:
          - docker-delegate
  notificationRules:
    - name: Failure-Email
      identifier: FailureEmail
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - jpestrada@unis.edu.gt
            - juanpablo08082002@hotmail.com
      enabled: true
