name: Sonarqube Scan
on:
 pull_request:
    branches:
      - main # the name of your main branch
      - dev
      - uat
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write # allows SonarQube to decorate PRs with analysis results
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('apex-airline-system/backend/**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: apex-airline-system/backend
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build jacocoTestReport sonarqube --info
        working-directory: apex-airline-system/backend
      - name: Send email notification
        if: failure() 
        uses: dawidd6/action-send-mail@v3
        with:
          from: 'spectrajenkins@gmail.com' # Replace with your email address
          to: 'jpestrada@unis.edu.gt' 
          subject: 'Build Failure Notification'
          body: |
            The build has failed. Please check the details in the GitHub Actions logs.
            Job: ${{ github.job }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.sha }}
          smtp-server: 'smtp.gmail.com'
          smtp-port: 587
          smtp-username: ${{ secrets.GMAIL_USERNAME }} # Your Gmail address
          smtp-password: ${{ secrets.GMAIL_APP_PASSWORD }} # Your Gmail App Password
          secure: true

